export {default as BasicsInformation} from '../components/auth/BasicsInformation';
export {default as EmergencyInformation} from '../components/auth/EmergencyInformation';
export {default as GenderInformation} from '../components/auth/GenderInformation';
export {default as IdentityAndBankInformation} from '../components/auth/IdentityAndBankInformation';
export {default as PreferAreaInformation} from '../components/auth/PreferAreaInformation';
export {default as SelectServicesInformation} from '../components/auth/SelectServicesInformation';
export {default as ServiceTypeInformation} from '../components/auth/ServiceTypeInformation';
export {default as VehicleInformation} from '../components/auth/VehicleInformation';
export {default as AppInput} from '../components/container/AppInput';
